version: 0.1.0.{build}
skip_tags: true
image: Visual Studio 2017
configuration: RelWithDebInfo
platform: x64

environment:
  access_token:
    secure: m3S5zoUHk9S/S5KkFi6MDNEwmxm2slLnbC91kMvYJZdvKwyGqDBj2sD9cAfBWShT

before_build:
- cmd: >-
    echo Building the commit %APPVEYOR_REPO_COMMIT%
        
    git submodule init

    git submodule update --init --recursive

    vcsetup.bat



build:
  project: build\gltf-insight.sln
  parallel: true
  verbosity: minimal
  
artifacts:
  - path: build\RelWithDebInfo\gltf-insight.exe
  - path: build\RelWithDebInfo\gltf-insight.pdb

before_deploy:
  - git config --global credential.helper store
  - ps: Add-Content "$HOME\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.name "A script on AppVeyor"
  - git config --global user.email "syoyo@lighttransport.com"
  - git tag -fa continuous-appveyor -m "Windows CI build tag"
  - git push origin :refs/tags/continuous-appveyor
  - git push origin continuous-appveyor 


deploy:
- provider: GitHub
  tag: continuous-appveyor
  release: "Windows continuous build"
  description: "AppVeyor build $(appveyor_repo_commit)"
  auth_token:
    secure: m3S5zoUHk9S/S5KkFi6MDNEwmxm2slLnbC91kMvYJZdvKwyGqDBj2sD9cAfBWShT
  prerelease: true
  force_update: true
  on:
    branch: devel

